services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx